name: luminash_booth
description: Photo booth launcher and booth flow inspired by Luminash.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  file_picker: ^12.0.0
  http: ^1.2.2
  http_parser: ^4.0.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/kamera.png
    - assets/images/sootjump.png
    - assets/images/bunnywave.png
